spring.application.name=lesson5

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=SYSTEM
spring.datasource.password=Ilopmcia651
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.key=mytokenkeymytokenkeymytokenkeymytokenkeymytokenkeymytokenkeymytokenkeymytokenkey

cors.allowed-origins=*
cors.allowed-methods=*
cors.allowed-headers=*
cors.exposed-headers=*

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.io.micrometer.tracing=DEBUG
logging.level.io.io.zipkin.reporter2=DEBUG
logging.level.com.coface.lesson5=TRACE

# logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.export.enabled=true
management.zipkin.tracing.endpoint=http://localhost:9411
